title: Insha Arshad | Data Scientist
# email: Confidential
description: About Me
baseurl: "/aboutme" 
url: "https://insha-a.github.io" 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Social Links
linkedin_username: insha-arshad
github_username: Insha-A
# gscholar_username: 
